export const COVER_PHOTOS = [
  {
    id: 'mountains',
    src: '/images/covers/mountains.jpg',
    alt: 'Snowy mountain peaks',
    credit: 'Kalen Emsley',
    creditUrl: 'https://unsplash.com/@kalenemsley?utm_source=northstar&utm_medium=referral',
  },
  {
    id: 'forest',
    src: '/images/covers/forest.jpg',
    alt: 'Sunlight through a forest',
    credit: 'Casey Horner',
    creditUrl: 'https://unsplash.com/@mischievous_penguins?utm_source=northstar&utm_medium=referral',
  },
  {
    id: 'beach',
    src: '/images/covers/beach.jpg',
    alt: 'Tropical beach',
    credit: 'Sean Oulashin',
    creditUrl: 'https://unsplash.com/@oulashin?utm_source=northstar&utm_medium=referral',
  },
  {
    id: 'lake',
    src: '/images/covers/lake.jpg',
    alt: 'Lake and mountains',
    credit: 'Pietro De Grandi',
    creditUrl: 'https://unsplash.com/@peter_mc_greats?utm_source=northstar&utm_medium=referral',
  },
  {
    id: 'night',
    src: '/images/covers/night.jpg',
    alt: 'Night sky over mountains',
    credit: 'Benjamin Voros',
    creditUrl: 'https://unsplash.com/@vorosbenis?utm_source=northstar&utm_medium=referral',
  },
  {
    id: 'desert',
    src: '/images/covers/desert.jpg',
    alt: 'Desert dunes',
    credit: 'Ken Cheung',
    creditUrl: 'https://unsplash.com/@kencheungphoto?utm_source=northstar&utm_medium=referral',
  },
  {
    id: 'city',
    src: '/images/covers/city.jpg',
    alt: 'City skyline at dusk',
    credit: 'Pedro Lastra',
    creditUrl: 'https://unsplash.com/@peterlaster?utm_source=northstar&utm_medium=referral',
  },
  {
    id: 'flowers',
    src: '/images/covers/flowers.jpg',
    alt: 'Field of flowers',
    credit: 'Sergey Shmidt',
    creditUrl: 'https://unsplash.com/@monsterjee?utm_source=northstar&utm_medium=referral',
  },
  {
    id: 'workspace',
    src: '/images/covers/workspace.jpg',
    alt: 'Notebook and coffee on a desk',
    credit: 'Andrew Neel',
    creditUrl: 'https://unsplash.com/@andrewtneel?utm_source=northstar&utm_medium=referral',
  },
] as const
